
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelDominio.User;
import view.tableModel.ClientsTableModel;

/**
 *
 * @author jpmon
 */
public class ClientsDesktop extends javax.swing.JFrame {
    
    private ClientsTableModel userModel;
    
    private void atualizaTabela() {
        ArrayList<User> listaUser = CryptoQuestionClient.ccont.getListaUser();
        
        userModel = new ClientsTableModel(listaUser);
        jTUser.setModel(userModel);
    }
    
     public void pesquisarTabela(){
        userModel = new ClientsTableModel(CryptoQuestionClient.ccont.getListaUserFiltro(jTFPesquisar.getText()));
        jTUser.setModel(userModel); //setando o modelo correto para a tabela do formulário
   }

    /**
     * Creates new form HomeDesktop
     */
    public ClientsDesktop() {
        initComponents();
        atualizaTabela();
        
        jLMensagemUsuario.setText("Olá! " + CryptoQuestionClient.ccont.user.getNameUser());
        setIconImage(getIconImage());
        }
    
    public final Image getIconImage() {
        Image icone = Toolkit.getDefaultToolkit().getImage("src/view/util/logoBarra.png");
        return icone;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBackGround = new javax.swing.JPanel();
        jLTaxa = new javax.swing.JLabel();
        jLHome = new javax.swing.JLabel();
        jTFPesquisar = new javax.swing.JTextField();
        jLOnOff = new javax.swing.JLabel();
        jLClients = new javax.swing.JLabel();
        jPBorda = new javax.swing.JPanel();
        jLLogo = new javax.swing.JLabel();
        jLMensagemUsuario = new javax.swing.JLabel();
        jLFotoPerfil = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUser = new javax.swing.JTable();
        jLMensagemUsuario1 = new javax.swing.JLabel();
        jBDeletarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clientes - Crypto Question");
        setResizable(false);

        jPBackGround.setBackground(new java.awt.Color(255, 255, 255));
        jPBackGround.setPreferredSize(new java.awt.Dimension(640, 400));

        jLTaxa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/taxa.png"))); // NOI18N
        jLTaxa.setToolTipText("Botão para tela Taxas.");
        jLTaxa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLTaxaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLTaxaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLTaxaMouseExited(evt);
            }
        });

        jLHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/home.png"))); // NOI18N
        jLHome.setToolTipText("Botão para Tela Inicial.");
        jLHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLHomeMouseClicked(evt);
            }
        });

        jTFPesquisar.setToolTipText("Faça a pesquisa do Usuário pelo seu Nome, Email, Data de Nascimento ou seu ID.");
        jTFPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPesquisarActionPerformed(evt);
            }
        });
        jTFPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFPesquisarKeyReleased(evt);
            }
        });

        jLOnOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/onoff.png"))); // NOI18N
        jLOnOff.setToolTipText("Botão para tela Encerrar o Programa.");
        jLOnOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLOnOffMouseClicked(evt);
            }
        });

        jLClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/clientsHover.png"))); // NOI18N
        jLClients.setToolTipText("Botão para tela Clientes.");
        jLClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLClientsMouseClicked(evt);
            }
        });

        jPBorda.setBackground(new java.awt.Color(217, 217, 217));
        jPBorda.setPreferredSize(new java.awt.Dimension(2, 0));

        javax.swing.GroupLayout jPBordaLayout = new javax.swing.GroupLayout(jPBorda);
        jPBorda.setLayout(jPBordaLayout);
        jPBordaLayout.setHorizontalGroup(
            jPBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPBordaLayout.setVerticalGroup(
            jPBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/logo.png"))); // NOI18N

        jLMensagemUsuario.setForeground(new java.awt.Color(25, 25, 25));
        jLMensagemUsuario.setText("Olá Administrador");

        jLFotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/fotoPerfil.png"))); // NOI18N

        jTUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTUser.setToolTipText("Tabela de Usuários.");
        jScrollPane1.setViewportView(jTUser);

        jLMensagemUsuario1.setForeground(new java.awt.Color(25, 25, 25));
        jLMensagemUsuario1.setText("Pesquisar Usuário");

        jBDeletarUsuario.setBackground(new java.awt.Color(255, 189, 34));
        jBDeletarUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBDeletarUsuario.setForeground(new java.awt.Color(2, 62, 116));
        jBDeletarUsuario.setText("Deletar Usuário");
        jBDeletarUsuario.setToolTipText("Botão para Deletar o Usuário Selecionado.");
        jBDeletarUsuario.setBorderPainted(false);
        jBDeletarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeletarUsuarioActionPerformed(evt);
            }
        });
        jBDeletarUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBDeletarUsuarioKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPBackGroundLayout = new javax.swing.GroupLayout(jPBackGround);
        jPBackGround.setLayout(jPBackGroundLayout);
        jPBackGroundLayout.setHorizontalGroup(
            jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBackGroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLOnOff)
                    .addComponent(jLHome)
                    .addComponent(jLClients)
                    .addComponent(jLTaxa))
                .addGap(18, 18, 18)
                .addComponent(jPBorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBackGroundLayout.createSequentialGroup()
                        .addGroup(jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPBackGroundLayout.createSequentialGroup()
                                .addGroup(jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPBackGroundLayout.createSequentialGroup()
                                        .addComponent(jLFotoPerfil)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLMensagemUsuario))
                                    .addComponent(jLMensagemUsuario1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLLogo))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
                        .addGap(24, 24, 24))
                    .addGroup(jPBackGroundLayout.createSequentialGroup()
                        .addComponent(jTFPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBDeletarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPBackGroundLayout.setVerticalGroup(
            jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBackGroundLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLHome)
                .addGap(61, 61, 61)
                .addComponent(jLTaxa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jLClients)
                .addGap(61, 61, 61)
                .addComponent(jLOnOff)
                .addGap(68, 68, 68))
            .addComponent(jPBorda, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jPBackGroundLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLLogo)
                    .addGroup(jPBackGroundLayout.createSequentialGroup()
                        .addGroup(jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLFotoPerfil)
                            .addGroup(jPBackGroundLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLMensagemUsuario)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLMensagemUsuario1)))
                .addGap(1, 1, 1)
                .addGroup(jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDeletarUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLHomeMouseClicked
        // TODO add your handling code here:
        HomeDesktop scrHome = new HomeDesktop();
        scrHome.setVisible(true); // chamando a tela form principal
        dispose(); // fechando  tela login
    }//GEN-LAST:event_jLHomeMouseClicked

    private void jLTaxaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTaxaMouseExited
        // TODO add your handling code here:
        // jLTaxa.setVisible(true);
    }//GEN-LAST:event_jLTaxaMouseExited

    private void jLTaxaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTaxaMouseEntered
        // TODO add your handling code here:
        // jLTaxa.setVisible(false);
    }//GEN-LAST:event_jLTaxaMouseEntered

    private void jLClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLClientsMouseClicked
        // TODO add your handling code here:
        ClientsDesktop scrClients = new ClientsDesktop();
        scrClients.setVisible(true); // chamando a tela form principal
        dispose(); // fechando  tela login
    }//GEN-LAST:event_jLClientsMouseClicked

    private void jLTaxaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTaxaMouseClicked
        // TODO add your handling code here:
        TaxaDesktop scrTaxa = new TaxaDesktop();
        scrTaxa.setVisible(true); // chamando a tela form principal
        dispose(); // fechando  tela login
    }//GEN-LAST:event_jLTaxaMouseClicked

    private void jLOnOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOnOffMouseClicked
        // TODO add your handling code here:
        OffDesktop scrOff = new OffDesktop();
        scrOff.setVisible(true); // chamando a tela form principal
        dispose(); // fechando  tela login
    }//GEN-LAST:event_jLOnOffMouseClicked

    private void jTFPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPesquisarActionPerformed

    private void jBDeletarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeletarUsuarioActionPerformed
        if (jTUser.getSelectedRow() >= 0) {
            if (JOptionPane.showConfirmDialog(this,
                "Tem certeza de que deseja excluir o usuário?",
                this.getTitle(),
                JOptionPane.YES_NO_OPTION)
            == JOptionPane.YES_OPTION) {

            User user = userModel.getUser(jTUser.getSelectedRow());
            if (user != null) {
                CryptoQuestionClient.ccont.deleteUser(user);
                atualizaTabela();
            }
        }
        }
    }//GEN-LAST:event_jBDeletarUsuarioActionPerformed

    private void jTFPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPesquisarKeyReleased
        // TODO add your handling code here:
        pesquisarTabela();
    }//GEN-LAST:event_jTFPesquisarKeyReleased

    private void jBDeletarUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBDeletarUsuarioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBDeletarUsuarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientsDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientsDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientsDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientsDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientsDesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDeletarUsuario;
    private javax.swing.JLabel jLClients;
    private javax.swing.JLabel jLFotoPerfil;
    private javax.swing.JLabel jLHome;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JLabel jLMensagemUsuario;
    private javax.swing.JLabel jLMensagemUsuario1;
    private javax.swing.JLabel jLOnOff;
    private javax.swing.JLabel jLTaxa;
    private javax.swing.JPanel jPBackGround;
    private javax.swing.JPanel jPBorda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFPesquisar;
    private javax.swing.JTable jTUser;
    // End of variables declaration//GEN-END:variables
}
