/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;

/**
 *
 * @author jpmon
 */
public class HomeDesktop extends javax.swing.JFrame {

    /**
     * Creates new form HomeDesktop
     */
    public HomeDesktop() {
        initComponents();
        jLMensagemUsuario.setText("Olá! " + CryptoQuestionClient.ccont.user.getNameUser());
        setIconImage(getIconImage());
        }
    
   public final Image getIconImage() {
        Image icone = Toolkit.getDefaultToolkit().getImage("src/view/util/logoBarra.png");
        return icone;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBackGround = new javax.swing.JPanel();
        jLTaxa = new javax.swing.JLabel();
        jLHome = new javax.swing.JLabel();
        jLOnOff = new javax.swing.JLabel();
        jLClients = new javax.swing.JLabel();
        jLUsuarioCadastrados = new javax.swing.JLabel();
        jPBorda = new javax.swing.JPanel();
        jLUsuarioAtivos = new javax.swing.JLabel();
        jLTransferencias = new javax.swing.JLabel();
        jLLogo = new javax.swing.JLabel();
        jLMensagemUsuario = new javax.swing.JLabel();
        jLTituloLucro = new javax.swing.JLabel();
        jLLucro = new javax.swing.JLabel();
        jLTituloTaxaAtual = new javax.swing.JLabel();
        jLTaxaAtual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLFotoPerfil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Inicial - Crypto Question");
        setResizable(false);

        jPBackGround.setBackground(new java.awt.Color(255, 255, 255));
        jPBackGround.setPreferredSize(new java.awt.Dimension(640, 400));

        jLTaxa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/taxa.png"))); // NOI18N
        jLTaxa.setToolTipText("Botão para tela Taxas.");
        jLTaxa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLTaxaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLTaxaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLTaxaMouseExited(evt);
            }
        });

        jLHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/homeHover.png"))); // NOI18N
        jLHome.setToolTipText("Botão para Tela Inicial.");
        jLHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLHomeMouseClicked(evt);
            }
        });

        jLOnOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/onoff.png"))); // NOI18N
        jLOnOff.setToolTipText("Botão para tela Encerrar o Programa.");
        jLOnOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLOnOffMouseClicked(evt);
            }
        });

        jLClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/clients.png"))); // NOI18N
        jLClients.setToolTipText("Botão para tela Clientes.");
        jLClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLClientsMouseClicked(evt);
            }
        });
        jLClients.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLClientsKeyPressed(evt);
            }
        });

        jLUsuarioCadastrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/usuarioCadastrados.png"))); // NOI18N
        jLUsuarioCadastrados.setToolTipText("Função Indisponível no Momento. Aqui será possível monitorar a quantidade de Usuários Cadastrados.");

        jPBorda.setBackground(new java.awt.Color(217, 217, 217));
        jPBorda.setPreferredSize(new java.awt.Dimension(2, 0));

        javax.swing.GroupLayout jPBordaLayout = new javax.swing.GroupLayout(jPBorda);
        jPBorda.setLayout(jPBordaLayout);
        jPBordaLayout.setHorizontalGroup(
            jPBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPBordaLayout.setVerticalGroup(
            jPBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLUsuarioAtivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/usuarioAtivo.png"))); // NOI18N
        jLUsuarioAtivos.setToolTipText("Função Indisponível no Momento. Aqui será possível monitorar a quantidade de Usuários Ativos no momento.");

        jLTransferencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/transferencias.png"))); // NOI18N
        jLTransferencias.setToolTipText("Função Indisponível no Momento. Aqui será possível monitorar a quantidade de Transferência realizadas na plataforma.");

        jLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/logo.png"))); // NOI18N

        jLMensagemUsuario.setForeground(new java.awt.Color(25, 25, 25));
        jLMensagemUsuario.setText("Olá Administrador");
        jLMensagemUsuario.setToolTipText("Função Indisponível no Momento. Aqui será aprsentado o nome do usuário.");

        jLTituloLucro.setForeground(new java.awt.Color(25, 25, 25));
        jLTituloLucro.setText("Lucro Realizado");

        jLLucro.setForeground(new java.awt.Color(84, 84, 84));
        jLLucro.setText("R$ 5.820,18");
        jLLucro.setToolTipText("Função Indisponível no Momento. Aqui será possível monitorar o lucro realizado pela plataforma");

        jLTituloTaxaAtual.setForeground(new java.awt.Color(25, 25, 25));
        jLTituloTaxaAtual.setText("Taxa Atual");

        jLTaxaAtual.setForeground(new java.awt.Color(84, 84, 84));
        jLTaxaAtual.setText("2,00%");
        jLTaxaAtual.setToolTipText("Função Indisponível no Momento. Aqui será possível monitorar a taxa cobrada atualmente na plataforma.");

        jScrollPane1.setToolTipText("Função Indisponível no Momento. Aqui será possível monitorar a atividade do Servidor.");

        jLFotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/fotoPerfil.png"))); // NOI18N
        jLFotoPerfil.setToolTipText("Função Indisponível no Momento. Aqui será possível visualizar a foto de perfil do usuáro.");

        javax.swing.GroupLayout jPBackGroundLayout = new javax.swing.GroupLayout(jPBackGround);
        jPBackGround.setLayout(jPBackGroundLayout);
        jPBackGroundLayout.setHorizontalGroup(
            jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBackGroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLOnOff)
                    .addComponent(jLHome)
                    .addComponent(jLClients)
                    .addComponent(jLTaxa))
                .addGap(18, 18, 18)
                .addComponent(jPBorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBackGroundLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLFotoPerfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLMensagemUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLLogo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBackGroundLayout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addGroup(jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPBackGroundLayout.createSequentialGroup()
                                .addComponent(jLUsuarioCadastrados)
                                .addGap(25, 25, 25)
                                .addComponent(jLUsuarioAtivos)
                                .addGap(25, 25, 25)
                                .addComponent(jLTransferencias)
                                .addGap(13, 13, 13)
                                .addGroup(jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLTituloLucro)
                                    .addComponent(jLTaxaAtual)
                                    .addGroup(jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLTituloTaxaAtual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLLucro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPBackGroundLayout.setVerticalGroup(
            jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBackGroundLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLHome)
                .addGap(61, 61, 61)
                .addComponent(jLTaxa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jLClients)
                .addGap(61, 61, 61)
                .addComponent(jLOnOff)
                .addGap(68, 68, 68))
            .addComponent(jPBorda, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jPBackGroundLayout.createSequentialGroup()
                .addGroup(jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBackGroundLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLLogo)
                            .addComponent(jLFotoPerfil)))
                    .addGroup(jPBackGroundLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLMensagemUsuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLTransferencias)
                    .addComponent(jLUsuarioAtivos)
                    .addComponent(jLUsuarioCadastrados)
                    .addGroup(jPBackGroundLayout.createSequentialGroup()
                        .addComponent(jLTituloLucro)
                        .addGap(6, 6, 6)
                        .addComponent(jLLucro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLTituloTaxaAtual)
                        .addGap(6, 6, 6)
                        .addComponent(jLTaxaAtual)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLTaxaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTaxaMouseEntered
        // TODO add your handling code here:
       // jLTaxa.setVisible(false);
    }//GEN-LAST:event_jLTaxaMouseEntered

    private void jLTaxaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTaxaMouseExited
        // TODO add your handling code here:
       // jLTaxa.setVisible(true);
    }//GEN-LAST:event_jLTaxaMouseExited

    private void jLHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLHomeMouseClicked
        // TODO add your handling code here:
        HomeDesktop scrHome = new HomeDesktop();
        scrHome.setVisible(true); // chamando a tela form principal
        dispose(); // fechando  tela login
    }//GEN-LAST:event_jLHomeMouseClicked

    private void jLTaxaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTaxaMouseClicked
        // TODO add your handling code here:
        TaxaDesktop scrTaxa = new TaxaDesktop();
        scrTaxa.setVisible(true); // chamando a tela form principal
        dispose(); // fechando  tela login
    }//GEN-LAST:event_jLTaxaMouseClicked

    private void jLClientsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLClientsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLClientsKeyPressed

    private void jLOnOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOnOffMouseClicked
        // TODO add your handling code here:
        OffDesktop scrOff = new OffDesktop();
        scrOff.setVisible(true); // chamando a tela form principal
        dispose(); // fechando  tela login
    }//GEN-LAST:event_jLOnOffMouseClicked

    private void jLClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLClientsMouseClicked
        // TODO add your handling code here:
        ClientsDesktop scrClients = new ClientsDesktop();
        scrClients.setVisible(true); // chamando a tela form principal
        dispose(); // fechando  tela login
    }//GEN-LAST:event_jLClientsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeDesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLClients;
    private javax.swing.JLabel jLFotoPerfil;
    private javax.swing.JLabel jLHome;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JLabel jLLucro;
    private javax.swing.JLabel jLMensagemUsuario;
    private javax.swing.JLabel jLOnOff;
    private javax.swing.JLabel jLTaxa;
    private javax.swing.JLabel jLTaxaAtual;
    private javax.swing.JLabel jLTituloLucro;
    private javax.swing.JLabel jLTituloTaxaAtual;
    private javax.swing.JLabel jLTransferencias;
    private javax.swing.JLabel jLUsuarioAtivos;
    private javax.swing.JLabel jLUsuarioCadastrados;
    private javax.swing.JPanel jPBackGround;
    private javax.swing.JPanel jPBorda;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
