/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import modelDominio.Admin;
import modelDominio.User;

/**
 *
 * @author lucas
 */
public class ScreenLogin extends javax.swing.JFrame {

    /**
     * Creates new form ScreenLogin
     */
    public ScreenLogin() {
        initComponents();
        jLMensagemLogin.setVisible(false);
        setIconImage(getIconImage());
        }
    
    public final Image getIconImage() {
        Image icone = Toolkit.getDefaultToolkit().getImage("src/view/util/logoBarra.png");
        return icone;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLEsqueciSenha = new javax.swing.JLabel();
        jPFSenha = new javax.swing.JPasswordField();
        jTFEmail = new javax.swing.JTextField();
        jBEntrar = new javax.swing.JButton();
        jLMensagemLogin = new javax.swing.JLabel();
        jLLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/logoScreenLogin.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 10)); // NOI18N
        jLabel4.setText("E-Mail:");

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 10)); // NOI18N
        jLabel5.setText("Senha");

        jLEsqueciSenha.setFont(new java.awt.Font("Sylfaen", 0, 10)); // NOI18N
        jLEsqueciSenha.setText("Esqueci a senha");
        jLEsqueciSenha.setToolTipText("Clique para redefinir a sua senha.");
        jLEsqueciSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLEsqueciSenhaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLEsqueciSenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLEsqueciSenhaMouseExited(evt);
            }
        });

        jPFSenha.setToolTipText("Informe a sua senha.");

        jTFEmail.setToolTipText("Informe o seu E-Mail.");
        jTFEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEmailActionPerformed(evt);
            }
        });

        jBEntrar.setBackground(new java.awt.Color(255, 189, 34));
        jBEntrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBEntrar.setForeground(new java.awt.Color(2, 62, 116));
        jBEntrar.setText("Entrar");
        jBEntrar.setToolTipText("Clique para entrar!");
        jBEntrar.setBorderPainted(false);
        jBEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEntrarActionPerformed(evt);
            }
        });

        jLMensagemLogin.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLMensagemLogin.setForeground(new java.awt.Color(255, 0, 0));
        jLMensagemLogin.setText("Usuário e/ou Senha inválido!");

        jLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/util/iconTelaLogin.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLLogo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLEsqueciSenha))
                    .addComponent(jPFSenha, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLMensagemLogin))
                            .addComponent(jTFEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jBEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLLogo)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLMensagemLogin))
                .addGap(1, 1, 1)
                .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(jPFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLEsqueciSenha)
                .addGap(47, 47, 47)
                .addComponent(jBEntrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEntrarActionPerformed
        // TODO add your handling code here:
        if (!jTFEmail.getText().equalsIgnoreCase("")) {
            if (!jPFSenha.getText().equalsIgnoreCase("")) {
                String email = jTFEmail.getText();
                String senha = jPFSenha.getText();
                
                User user = new User(email, senha);
        
                User usuarioLogado = CryptoQuestionClient.ccont.efetuarLogin(user);
                if (usuarioLogado != null) {
                    if (usuarioLogado instanceof Admin) {
                        CryptoQuestionClient.ccont.user = usuarioLogado;
                        HomeDesktop scrHome = new HomeDesktop();
                        scrHome.setVisible(true); // chamando a tela form principal
                        dispose(); // fechando  tela login
                    } else {
                        JOptionPane.showMessageDialog(this, "Você está entrando com uma conta do tipo CLIENTE e não ADMNIN!", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                        jPFSenha.requestFocus();
                    }
                } else {
                    jLMensagemLogin.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Preencha com alguma senha!", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                jPFSenha.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Preencha com algum e-mail!", this.getTitle(), JOptionPane.ERROR_MESSAGE);
            jTFEmail.requestFocus();
        }
    }//GEN-LAST:event_jBEntrarActionPerformed

    private void jTFEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEmailActionPerformed

    private void jLEsqueciSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLEsqueciSenhaMouseClicked
        // TODO add your handling code here:
        ValidaEmail redSenha = new ValidaEmail();
        redSenha.setVisible(true); // chamando a tela form principal

    }//GEN-LAST:event_jLEsqueciSenhaMouseClicked

    private void jLEsqueciSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLEsqueciSenhaMouseEntered
        // TODO add your handling code here:
        jLEsqueciSenha.setForeground(Color.decode("#FFBD22"));
        
    }//GEN-LAST:event_jLEsqueciSenhaMouseEntered

    private void jLEsqueciSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLEsqueciSenhaMouseExited
        // TODO add your handling code here:
        jLEsqueciSenha.setForeground(Color.black);
    }//GEN-LAST:event_jLEsqueciSenhaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEntrar;
    private javax.swing.JLabel jLEsqueciSenha;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JLabel jLMensagemLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFEmail;
    // End of variables declaration//GEN-END:variables
}
